sources:
  - ComicRelief-Regular.ufo
  - ComicRelief-Bold.ufo
familyName: "Comic Relief"
outputDir: "../fonts"
buildOTF: false
googleFonts: true
removeOutlineOverlaps: false
buildVariable: false
#autohintTTF: false
